local action={
    ["player"]={
            ["stand"]   ={[[roles/player1-1-%d.png]] , 1 , "stand"    , 0.1},
            ["walk"]     ={[[roles/player1-1-%d.png]] , 4  ,"walk"     , 0.1},
            ["attack1"] ={[[roles/player1-2-%d.png]] , 4 , "attack1" , 0.1},
            ["attack2"] ={[[roles/player1-5-%d.png]] , 4 , "attack2" , 0.1},
            ["hit"]        ={[[roles/player1-4-%d.png]] , 2 , "hit"        , 0.1},
            ["die"]       ={[[roles/player1-3-%d.png]] , 4 , "die"       , 0.1},
            ["super"]    =[[playerSuper]],
            ["child"]     =[[player]],
            ["anchorX"] =0.43,
            ["scale"]      =0.3,
            ["colorBox"] =true,
            ["sizeNode"]       =cc.size(35,45),
            ["pos"]       =cc.p(35/2+13,-13),
            ["move"] = {
                    ["left"]    = {  "left" , -20 , -1},
                    ["right"]  = {"right" , 20  ,  1},
                    ["up"]     = {  "up" , 20 , 1},
                    ["down"] = {  "down" , -20 , 1},
            },
    },
    ["enemy_1"]={
            ["stand"]   ={[[roles/enemy1-1-%s.png]] , 1 , "stand"    , 0.1},
            ["walk"]     ={[[roles/enemy1-1-%d.png]] , 3  ,"walk"     , 0.1},
            ["attack1"] ={[[roles/enemy1-2-%d.png]] , 3 , "attack1" , 0.1},
            ["attack2"] ={[[roles/enemy1-2-%d.png]] , 3 , "attack2" , 0.1},
            ["hit"]        ={[[roles/enemy1-4-%d.png]] , 2 , "hit"        , 0.1},
            ["die"]       ={[[roles/enemy1-3-%d.png]] , 3 , "die"       , 0.1},
            ["super"]    =[[enemySuper_1]],
            ["child"]     =[[enemy_1]],
            ["anchorX"] =0.56,
            ["scale"]      =0.35,
            ["colorBox"] =true,
            ["sizeNode"]       =cc.size(35,45),
            ["pos"]       =cc.p(35/2-15,-5),
            ["move"] = {
                    ["left"]   = {  "left" , -10 ,  1},
                    ["right"] = {"right" , 10  , -1},
                    ["up"]     = {  "up" , 10 , 1},
                    ["down"] = {  "down" , -10 , 1},
            },
    },
    ["enemy_2"]={
            ["stand"]   ={[[roles/enemy2-1-%s.png]] , 1 , "stand"    , 0.1},
            ["walk"]     ={[[roles/enemy2-1-%d.png]] , 3  ,"walk"     , 0.1},
            ["attack1"] ={[[roles/enemy2-2-%d.png]] , 3 , "attack1" , 0.1},
            ["attack2"] ={[[roles/enemy2-2-%d.png]] , 3 , "attack2" , 0.1},
            ["hit"]        ={[[roles/enemy2-4-%d.png]] , 2 , "hit"        , 0.1},
            ["die"]       ={[[roles/enemy2-3-%d.png]] , 3 , "die"       , 0.1},
            ["super"]    =[[enemySuper_2]],
            ["child"]     =[[enemy_2]],
            ["anchorX"] =0.56,
            ["scale"]      =0.35,
            ["colorBox"] =true,
            ["sizeNode"]       =cc.size(35,45),
            ["pos"]       =cc.p(35/2-15,-5),
            ["move"] = {
                    ["left"]   = {  "left" , -10 ,  1},
                    ["right"] = {"right" , 10  , -1},
                    ["up"]     = {  "up" , 10 ,  1},
                    ["down"] = {  "down" , -10 , 1},
            },
    },
    ["df"]={
            ["stand"]   ={[[roles/df1-1-%s.png]] , 1 , "stand"    , 0.1},
            ["walk"]     ={[[roles/df1-1-%d.png]] , 1  ,"walk"     , 0.1},
            ["attack1"] ={[[roles/df1-2-%d.png]] , 5 , "attack1" , 0.1},
            ["attack2"] ={[[roles/df1-2-%d.png]] , 5 , "attack2" , 0.1},
            ["hit"]        ={[[roles/df1-4-%d.png]] , 2 , "hit"        , 0.1},
            ["die"]       ={[[roles/df1-3-%d.png]] , 4 , "die"       , 0.1},
            ["super"]    =[[enemySuper_2]],
            ["child"]     =[[enemy_2]],
            ["anchorX"] =0.56,
            ["scale"]      =0.3,
            ["colorBox"] =true,
            ["sizeNode"]       =cc.size(50,60),
            ["pos"]       =cc.p(35/2-12,-5),
            ["move"] = {
                    ["left"]   = {  "left" , -10 ,  1},
                    ["right"] = {"right" , 20  , -1},
                    ["up"]     = {  "up" , 10 , 1},
                    ["down"] = {  "down" , -10 , 1},
            },
    },
}
return action